import {test} from 'node:test';import assert from 'node:assert/strict';
import core from '../web/simulation.js';
import {addInvestors,makeOffer,settleLot,totalCash,assertFinance,runAuction,joinPlayer,liquidate,liquidationQuote,shareCount,valuation,operatingBalances,finishOperations} from '../web/investors.js';
import {addEconomy,spendPlans,afterOperations,updateDemand,productionRevenue} from '../web/economy.js';
import {validateAnswer} from '../web/client.js';
const town=()=>addEconomy(addInvestors(core.createTown()));
const fake=action=>async reqs=>Object.fromEntries(reqs.map(r=>[r.id,{decision:{type:'choice',choice:action,confidence:.9,probabilities:{bid:action==='bid'?.9:.1,pass:action==='pass'?.9:.1}}}]));
function buy(t,id='market10',iid='i0',amount){const o=makeOffer(t,id);o.status='open';o.highBid=amount||o.reserve;o.highBidder=iid;settleLot(t,o);return o;}
test('preserves town topology; five distinct autonomous investors',()=>{const t=town();assert.equal(t.residents.length,120);assert.equal(t.places.length,58);assert.equal(Object.keys(t.businesses).length,17);assert.equal(t.investors.length,5);assert.equal(t.residents.reduce((n,r)=>n+r.money,0),6023);assert.equal(t.treasury,600);});
test('ascending auction rotates, terminates, pays once and conserves money',async()=>{const t=town(),o=makeOffer(t,'market10'),before=totalCash(t);await runAuction(t,o,fake('bid'));assert.equal(o.status,'funded');assert.ok(o.bids.length>1);assert.ok(new Set(o.bids.map(b=>b.investorId)).size>=2);assert.equal(totalCash(t),before);assert.ok(o.bids.every((b,n)=>!n||b.amount>o.bids[n-1].amount));assert.throws(()=>settleLot(t,o),/already/);assertFinance(t);});
test('all pass yields no buyer, no transfer, no shares',async()=>{const t=town(),o=makeOffer(t,'market10'),before=totalCash(t);await runAuction(t,o,fake('pass'));assert.equal(o.status,'no-buyer');assert.equal(t.finance.ledger.length,0);assert.equal(totalCash(t),before);assert.equal(shareCount(t.businesses.market10),10000);});
test('human bid and pass stay under human callback control',async()=>{const t=town(),p=joinPlayer(t),o=makeOffer(t,'market10');let turns=0;await runAuction(t,o,fake('pass'),{humanTurn:async()=>{turns++;return 'bid';}});assert.equal(turns,1);assert.equal(o.highBidder,p.id);assert.ok(p.cash<2200);});
test('liquidation is immediate, share/cash conserving and not a new-issue money printer',()=>{const t=town(),p=joinPlayer(t),before=totalCash(t),o=buy(t,'market10',p.id);const b=t.businesses.market10,supply=shareCount(b),cash=b.till,quote=liquidationQuote(t,p,'market10',o.shares);assert.ok(quote<o.amount);liquidate(t,p,'market10',o.shares);assert.equal(shareCount(b),supply);assert.equal(b.till,cash);assert.equal(totalCash(t),before);assert.ok(p.cash<2200);assert.equal(b.capital.marketShares,o.shares);assert.throws(()=>liquidate(t,p,'market10',1),/share/);});
test('no dividend/profit distribution; current cash is excluded from operating gains',()=>{const t=town(),o=buy(t),i=t.investors[0],cash=i.cash;const open=operatingBalances(t);t.businesses.market10.till+=1000;t.businesses.market10.revenue+=1000;t.hour=24;finishOperations(t,open);assert.equal(i.cash,cash);assert.ok(t.finance.ledger.every(x=>x.kind!=='dividend'));assert.equal(t.businesses.market10.capital.lastDayProfit,1000);});
test('capital plan spends cash and owner skill materially changes delivery',()=>{const t=town(),a=t.businesses.market9,b=t.businesses.market10;for(const x of [a,b]){x.till=2000;x.economy.plan={type:'expand',product:'value',cost:500,stage:'needs funding'};}a.economy.owner.adaptability=90;b.economy.owner.adaptability=10;spendPlans(t);assert.equal(a.till,1500);assert.ok(a.economy.plan.ready<b.economy.plan.ready);t.hour=10;spendPlans(t);assert.ok(a.economy.capacity>b.economy.capacity);assert.equal(t.economy.supplierCash,1000);});
test('demand changes producer receipts; genuine failure writes equity to zero',()=>{const t=town(),r=t.residents.find(r=>t.places.find(p=>p.id===r.work).kind==='office'),b=t.businesses[r.work];updateDemand(t);b.economy.product='value';t.economy.demand={value:120,wellness:0,experience:0};const hot=productionRevenue(t,r,20);t.economy.demand={value:0,wellness:120,experience:0};assert.ok(productionRevenue(t,r,20)<hot);const failedId=r.work;b.till=0;b.economy.strain=11;t.hour=25;afterOperations(t,operatingBalances(t));assert.equal(b.economy.failed,true);assert.equal(valuation(t,failedId).value,0);});
test('malformed model answers rejected',()=>{const q={type:'choice',criteria:{yes:'yes',no:'no'}};assert.throws(()=>validateAnswer(q,{type:'choice',choice:'invented',confidence:.9,probabilities:{yes:.5,no:.5}}));});
